version: '3.8'
services:
  backend:
    build: .
    container_name: tarefai_backend
    ports:
      - "8000:8000"
    environment:
      - LLM_PROVIDER=spacy
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload 